### ISSUE TITLE
Circular dependency error on multi-project builds with same project names

### ISSUE THREAD

**Issue by Archengius** [google/protobuf-gradle-plugin#330]
Imagine a project with the following graph:
```
Root:
  - ServiceAPIs:
      - Example - API of Example service
         - protobuf definition files here
  - Services:
      - Example - service API implementation
          - compile dependency on :ServiceAPIs:Example
```
When building :Services:Example project with protobuf-gradle, gradle reports circular dependency. Example circular dependency graph as reported by gradle:
```
Circular dependency between the following tasks:
:Services:Example:classes
\--- :Services:Example:compileJava
     +--- :Services:Example:compileKotlin
     |    +--- :Services:Example:generateProto
     |    |    \--- :Services:Example:extractIncludeProto
     |    |         \--- :Services:Example:jar
     |    |              +--- :Services:Example:classes (*)
     |    |              +--- :Services:Example:compileKotlin (*)
     |    |              \--- :Services:Example:inspectClassesForKotlinIC
     |    |                   \--- :Services:Example:classes (*)
     |    \--- :Services:Example:jar (*)
     +--- :Services:Example:generateProto (*)
     \--- :Services:Example:jar (*)
```
